/* One-off: self-host the Google Fonts used by the site (Poppins).
   Downloads ONLY the latin + latin-ext subsets (English content) as woff2 into
   assets/fonts/, and writes css/fonts.css with @font-face rules pointing at the
   local files (font-display: swap preserved). This removes the render-blocking
   third-party Google Fonts stylesheet and the two preconnects.
   Run: node scripts/fetch-fonts.js   (re-run only if the font request changes) */
const fs = require("fs");
const path = require("path");
const https = require("https");

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap";
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";
const KEEP = new Set(["latin", "latin-ext"]); // English site: skip cyrillic/greek/vietnamese
const fontsDir = path.join(__dirname, "..", "assets", "fonts");
const cssOut = path.join(__dirname, "..", "css", "fonts.css");

const get = (url, bin = false) =>
  new Promise((resolve, reject) => {
    https
      .get(url, { headers: { "User-Agent": UA } }, (res) => {
        if (res.statusCode !== 200) return reject(new Error(`${res.statusCode} ${url}`));
        const chunks = [];
        res.on("data", (c) => chunks.push(c));
        res.on("end", () => resolve(bin ? Buffer.concat(chunks) : Buffer.concat(chunks).toString("utf8")));
      })
      .on("error", reject);
  });

(async () => {
  fs.mkdirSync(fontsDir, { recursive: true });
  const css = await get(CSS_URL);

  // Split into "/* subset */ @font-face {...}" units.
  const units = css.split("@font-face").slice(1);
  let subset = "latin";
  // Recover the subset comment that precedes each block by scanning sequentially.
  const blocks = [];
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*@font-face\s*{([^}]*)}/g;
  let m;
  while ((m = re.exec(css))) blocks.push({ subset: m[1], body: m[2] });

  const downloaded = new Map(); // remote url -> local filename
  const rules = [];
  for (const b of blocks) {
    if (!KEEP.has(b.subset)) continue;
    const family = (b.body.match(/font-family:\s*'([^']+)'/) || [])[1];
    const weight = (b.body.match(/font-weight:\s*([^;]+);/) || [])[1].trim();
    const url = (b.body.match(/url\((https:[^)]+\.woff2)\)/) || [])[1];
    if (!family || !url) continue;
    let local = downloaded.get(url);
    if (!local) {
      const safe = family.toLowerCase();
      local = `${safe}-${b.subset}-${downloaded.size + 1}.woff2`;
      const buf = await get(url, true);
      fs.writeFileSync(path.join(fontsDir, local), buf);
      downloaded.set(url, local);
      console.log(`  ↓ ${local}  (${(buf.length / 1024).toFixed(1)} KB)  ${family} ${weight} ${b.subset}`);
    }
    const body = b.body
      .replace(/url\(https:[^)]+\.woff2\)/, `url(../assets/fonts/${local})`)
      .replace(/\s+/g, " ")
      .trim();
    rules.push(`/* ${family} ${weight} ${b.subset} */\n@font-face { ${body} }`);
  }

  const header = `/* Self-hosted fonts — generated by scripts/fetch-fonts.js. Do not edit by hand.
   Latin + latin-ext subsets of Poppins (font-display: swap). */\n`;
  fs.writeFileSync(cssOut, header + rules.join("\n") + "\n");
  console.log(`\nWrote ${cssOut} with ${rules.length} @font-face rules, ${downloaded.size} woff2 files.`);
})();
